services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: campaign_manager_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
